---
title: "Systematic Review Extraction Script Template"
date: "14 Sep 2018 at 15:31:30"
output:
  html_document:
    self-contained: yes
    toc: false
params:
  rxsVersion = "0.1.0"
---

```{r setup, include=FALSE, messages=FALSE}
### First load (and perhaps install) userfriendlyscience
if (!require('userfriendlyscience')) {
  install.packages('userfriendlyscience');
  require('userfriendlyscience');
}

### Other packages
safeRequire('googlesheets');     ### To import data from google sheets in metabefor
safeRequire('jsonlite');         ### To import a list of country codes in metabefor
safeRequire('data.tree');        ### To work with data structured in a tree in metabefor
safeRequire('pander');           ### To print the dataframe with results in a nice way
safeRequire('devtools');         ### To install metabefor from github repo
                                 ### ... Which we then do here:
devtools::install_github('Matherion/metabefor',
                         quiet=TRUE);
require('metabefor');            ### ... After which we load it

### Settings
knitr::opts_chunk$set(echo = FALSE);             ### Suppress R command printing
knitr::opts_chunk$set(comment=NA);               ### Suppress output prefix
pander::panderOptions('table.split.table', Inf); ### Disable table splitting
```

```{r fieldname-chunk}
eC <- list(titleCol="title",
           descriptionCol="description",
           identifierCol="identifier",
           valueTemplateCol="valueTemplate",
           validValuesCol="validValues",
           defaultCol="default",
           parentCol="parent",
           entityRefCol="entityRef",
           fieldRefCol="fieldRef",
           ownerCol="owner",
           listCol="list",
           collapsingCol="collapsing",
           repeatingCol="repeating",
           recurringCol="recurring",
           recursingCol="recursing",
           identifyingCol="identifying");

valueTemplateCols <- list(identifierCol="identifier",
                          descriptionCol="description",
                          validValuesCol="validValues",
                          defaultCol="default",
                          examplesCol="examples",
                          validationCol="validation",
                          errorCol="error");
```

```{r rxsChunk, echo=FALSE}
################################################################################
######################################################## START: study (ROOT) ###
################################################################################
study <- Node$new('study');
################################################################################

  ##############################################################################
  ########################################################### START: studyId ###
  ##############################################################################
  study$AddChild('studyId');
  study$studyId[['value']] <-
  ##############################################################################
  ### 
  ### STUDY IDENTIFIER
  ### 
  ### Unique identifier for this study
  ### 
  ##############################################################################
      
      "enter xdoi here"
      
  ##############################################################################
  ########################################### VALUE DESCRIPTION AND EXAMPLES ###
  ##############################################################################
  ### 
  ### For studies with a DOI, "doi:" directly followed by the DOI; for
  ### studies without a DOI, the DOI prefix of the publisher (see
  ### https://gist.github.com/TomDemeranville/8699224), followed by a
  ### slash, followed by the ISSN, followed by a dash, followed by the
  ### year of publication, followed by a dash, followed by the starting
  ### page. If no DOI prefix can be located, instead use 'NA'.
  ### 
  ### EXAMPLES:
  ### 
  ### "doi:10.18637/jss.v036.i03"
  ### "nodoi:10.1111/0965-2140/2003-951"
  ### "doi:10.1136/bmj.2.2288.1243"
  ### 
  ##############################################################################
  study$studyId[['validation']] <- expression(nchar(VALUE)>10);
  ##############################################################################
  ############################################################# END: studyId ###
  ##############################################################################


  ##############################################################################
  ########################################################## START: comments ###
  ##############################################################################
  study$AddChild('comments');
  study$comments[['value']] <-
  ##############################################################################
  ### 
  ### GENERAL COMMENTS
  ### 
  ### Any general comments the coder wants to add about this study
  ### 
  ##############################################################################
      
      ""
      
  ##############################################################################
  ########################################### VALUE DESCRIPTION AND EXAMPLES ###
  ##############################################################################
  ### 
  ### A single character value
  ### 
  ### EXAMPLES:
  ### 
  ### "Example"
  ### "Another example"
  ### 
  ##############################################################################
  study$comments[['validation']] <- expression(is.na(VALUE) || (is.character(VALUE) && length(VALUE) == 1));
  ##############################################################################
  ############################################################ END: comments ###
  ##############################################################################


  ##############################################################################
  ############################################################## START: year ###
  ##############################################################################
  study$AddChild('year');
  study$year[['value']] <-
  ##############################################################################
  ### 
  ### YEAR
  ### 
  ### Year (or years) the data were collected
  ### 
  ##############################################################################
      
      NA
      
  ##############################################################################
  ########################################### VALUE DESCRIPTION AND EXAMPLES ###
  ##############################################################################
  ### 
  ### A numeric vector of years
  ### 
  ### EXAMPLES:
  ### 
  ### 2001
  ### c(2001, 2002)
  ### 
  ##############################################################################
  study$year[['validation']] <- expression(is.na(VALUE) || (is.numeric(VALUE) && all(nchar(VALUE)==4)));
  ##############################################################################
  ################################################################ END: year ###
  ##############################################################################


  ##############################################################################
  ########################################################### START: country ###
  ##############################################################################
  study$AddChild('country');
  study$country[['value']] <-
  ##############################################################################
  ### 
  ### COUNTRY
  ### 
  ### Country (or countries) where the data were collected
  ### 
  ##############################################################################
      
      NA
      
  ##############################################################################
  ########################################### VALUE DESCRIPTION AND EXAMPLES ###
  ##############################################################################
  ### 
  ### A character vector of the ISO 3166-1 alpha-2 country code(s)
  ### 
  ### EXAMPLES:
  ### 
  ### "NL"
  ### c("NL", "BE")
  ### 
  ##############################################################################
  study$country[['validation']] <- expression(is.na(VALUE) || (VALUE %in% countryCodeList()));
  ##############################################################################
  ############################################################# END: country ###
  ##############################################################################


  ##############################################################################
  ########################################################### START: methods ###
  ##############################################################################
  study$AddChild('methods');
  ##############################################################################
  ### 
  ### METHODS
  ### 
  ### Description of the methods used by the study
  ### 
  ##############################################################################
      
  
    ############################################################################
    ############################################################### START: N ###
    ############################################################################
    study$methods$AddChild('N');
    study$methods$N[['value']] <-
    ############################################################################
    ### 
    ### SAMPLE SIZE
    ### 
    ### Total number of human participants in the study (note: the
    ### actual sample size may be larger if multiple observations are
    ### collected per participant)
    ### 
    ############################################################################
        
        NA
        
    ############################################################################
    ######################################### VALUE DESCRIPTION AND EXAMPLES ###
    ############################################################################
    ### 
    ### Any valid whole number
    ### 
    ### EXAMPLES:
    ### 
    ### 30
    ### 8762
    ### 
    ############################################################################
    study$methods$N[['validation']] <- expression(is.na(VALUE) || (is.numeric(VALUE) && (VALUE%%1==0) && (length(VALUE) == 1)));
    ############################################################################
    ################################################################# END: N ###
    ############################################################################
  
  
    ############################################################################
    ########################################### START: subsample (REPEATING) ###
    ############################################################################
    study$methods$AddChild('subsample__1__');
    study$methods$subsample__1__[['value']] <-
    ############################################################################
    ### 
    ### SUBSAMPLE
    ### 
    ### If studies contain several samples, specify them here
    ### 
    ############################################################################
        
        list(subsample.name = "Enter name here (mandatory)",  ### Name: A unique name (in this study), to be able to refer to this subsample later, and to easily find it afterwards [Examples: "Example"] [Value description: A single character value that cannot be omitted]
             subsample.N = NA);                               ### Size: Sample size of subsample [Examples: "Another example"] [Value description: Any valid whole number]
        
    ############################################################################
    study$methods$subsample__1__[['validation']] <- list(`subsample.name` = expression(!is.na(VALUE) && !is.null(VALUE) && (nchar(VALUE) > 0)),
                                                         `subsample.N` = expression(is.na(VALUE) || (is.numeric(VALUE) && (VALUE%%1==0) && (length(VALUE) == 1))));
    study$methods$subsample__1__$name <- study$methods$subsample__1__$value[[1]];
    ############################################################################
    ############################################# END: subsample (REPEATING) ###
    ############################################################################
  
  
    ############################################################################
    ###################################################### START: methodType ###
    ############################################################################
    study$methods$AddChild('methodType');
    study$methods$methodType[['value']] <-
    ############################################################################
    ### 
    ### TYPE OF STUDY
    ### 
    ### Whether the study was qualitative, quantitative, mixed methods,
    ### or a review
    ### 
    ############################################################################
        
        NA
        
    ############################################################################
    ######################################### VALUE DESCRIPTION AND EXAMPLES ###
    ############################################################################
    ### 
    ### A string that has to exactly match one of the values specified
    ### in the "values" column of the Coding sheet
    ### 
    ### EXAMPLE:
    ### 
    ### c("qualitative", "quantitative", "mixed methods", "review")
    ### 
    ############################################################################
    study$methods$methodType[['validation']] <- expression(is.na(VALUE) || (VALUE %in% c("qualitative", "quantitative", "mixed methods", "review")));
    ############################################################################
    ######################################################## END: methodType ###
    ############################################################################
  
  
    ############################################################################
    ####################################################### START: variables ###
    ############################################################################
    study$methods$AddChild('variables');
    ############################################################################
    ### 
    ### VARIABLES
    ### 
    ### The variables as used/observed in this study (i.e.
    ### operationalisations or an aspects)
    ### 
    ############################################################################
        
    
      ##########################################################################
      ################################ START: operationalisation (REPEATING) ###
      ##########################################################################
      study$methods$variables$AddChild('operationalisation__1__');
      study$methods$variables$operationalisation__1__[['value']] <-
      ##########################################################################
      ### 
      ### OPERATIONALISATION
      ### 
      ### An operationalisation (measurement or manipulation) used in
      ### the study
      ### 
      ##########################################################################
          
          list(oper.name = "Enter name here (mandatory)",  ### Operationalisation Name: A unique name (in this study), to be able to refer to this operationalisation later, and to easily find it afterwards [Examples: "Example"; "Another example"] [Value description: A single character value that cannot be omitted]
               oper.moment = 1,                            ### Moment: Moment(s) this variable was measured/manipulated. [Examples: c(23, 62); 52; c(76, 12, 42)] [Value description: A vector of integers (i.e. one or more whole numbers)]
               oper.type = NA,                             ### Type of operationalisation: Whether this variable is a manipulation, a single measurement, or an aggregate [Examples: c("manipulation", "item", "aggregate")] [Value description: A string that has to exactly match one of the values specified in the "values" column of the Coding sheet]
               oper.datatype = NA,                         ### Type of data: "Measurement level" of this operationalisation. [Examples: c("numeric", "logical", "nominal", "ordinal", "string")] [Value description: A string that has to exactly match one of the values specified in the "values" column of the Coding sheet]
               oper.values = NA,                           ### Values: Possible values this variable can take: only valid for "nominal" or "ordinal" variables. [Examples: c(23, 62); 52; c(76, 12, 42)] [Value description: A vector of integers (i.e. one or more whole numbers)]
               oper.labels = NA,                           ### Labels: Labels for the values. [Examples: c("First value", "Second value")] [Value description: A character vector (i.e. one or more strings)]
               oper.description = "",                      ### Description: A description of this variable (can be more extensive than the name) [Examples: "Example"; "Another example"] [Value description: A single character value]
               oper.comment = "");                         ### Comment: Any relevant comments the coder wants to add [Examples: "Example"; "Another example"] [Value description: A single character value]
          
      ##########################################################################
      study$methods$variables$operationalisation__1__[['validation']] <- list(`oper.name` = expression(!is.na(VALUE) && !is.null(VALUE) && (nchar(VALUE) > 0)),
                                                                              `oper.moment` = expression(is.na(VALUE) || (is.numeric(VALUE) && all(VALUE%%1==0))),
                                                                              `oper.type` = expression(is.na(VALUE) || (VALUE %in% c("manipulation", "item", "aggregate"))),
                                                                              `oper.datatype` = expression(is.na(VALUE) || (VALUE %in% c("numeric", "logical", "nominal", "ordinal", "string"))),
                                                                              `oper.values` = expression(is.na(VALUE) || (is.numeric(VALUE) && all(VALUE%%1==0))),
                                                                              `oper.labels` = expression(is.na(VALUE) || (is.character(VALUE))),
                                                                              `oper.description` = expression(is.na(VALUE) || (is.character(VALUE) && length(VALUE) == 1)),
                                                                              `oper.comment` = expression(is.na(VALUE) || (is.character(VALUE) && length(VALUE) == 1)));
      study$methods$variables$operationalisation__1__$name <- study$methods$variables$operationalisation__1__$value[[1]];
      ##########################################################################
      ################################## END: operationalisation (REPEATING) ###
      ##########################################################################
    
    
      ##########################################################################
      ############################################ START: aspect (REPEATING) ###
      ##########################################################################
      study$methods$variables$AddChild('aspect__1__');
      study$methods$variables$aspect__1__[['value']] <-
      ##########################################################################
      ### 
      ### ASPECT
      ### 
      ### An aspect (part of human psychology) reported in this study
      ### 
      ##########################################################################
          
          list(asp.content = "Aspect text",  ### Content: The content of the aspect, literally as reported in the study [Examples: "Example"] [Value description: A single character value that cannot be omitted]
               asp.description = "",         ### Description: A description of this variable (can be more extensive than the name) [Examples: "Another example"] [Value description: A single character value]
               asp.comment = "");            ### Comment: Any relevant comments the coder wants to add [Examples: "Example"] [Value description: A single character value]
          
      ##########################################################################
      study$methods$variables$aspect__1__[['validation']] <- list(`asp.content` = expression(!is.na(VALUE) && !is.null(VALUE) && (nchar(VALUE) > 0)),
                                                                  `asp.description` = expression(is.na(VALUE) || (is.character(VALUE) && length(VALUE) == 1)),
                                                                  `asp.comment` = expression(is.na(VALUE) || (is.character(VALUE) && length(VALUE) == 1)));
      study$methods$variables$aspect__1__$name <- study$methods$variables$aspect__1__$value[[1]];
      ##########################################################################
      ############################################## END: aspect (REPEATING) ###
      ##########################################################################
    
        
    ############################################################################
    ######################################################### END: variables ###
    ############################################################################
  
      
  ##############################################################################
  ############################################################# END: methods ###
  ##############################################################################


  ##############################################################################
  ########################################################### START: results ###
  ##############################################################################
  study$AddChild('results');
  ##############################################################################
  ### 
  ### RESULTS
  ### 
  ### Results based on the data collected in this study
  ### 
  ##############################################################################
      
  
    ############################################################################
    ########################################## START: univariate (REPEATING) ###
    ############################################################################
    study$results$AddChild('univariate__1__');
    study$results$univariate__1__[['value']] <-
    ############################################################################
    ### 
    ### UNIVARIATE
    ### 
    ### A single statistic about a single variable.
    ### 
    ############################################################################
        
        list(uni.name = "Enter name here (mandatory)",   ### Name of result: A unique name (in this study), to easily find / meta-analyse / group this result later [Examples: "prevalence"; "reliability"] [Value description: A single character value that cannot be omitted]
             uni.variable = "enter <<entityRef>> here",  ### Variable: The variable this result pertains to. [Examples: <no example>] [Value description: A string that specifies another entity and which MUST be provided]
             uni.subsample = NA,                         ### Subsample: If applicable, the subsample this result pertains to. [Examples: <no example>] [Value description: A string that specifies another entity (can be missing, i.e. NA)]
             uni.value = NA,                             ### Value: If applicable, the value this result pertains to. For example, for a categorical variable, three percentages can be specified: one for each possible category (as identified by the corresponding value). [Examples: <no example>] [Value description: A string that specifies another field in another entity (can be missing, i.e. NA).]
             uni.moment = NA,                            ### Moment: If applicable, the measurement moemnt this result pertains to. For example, for a longitudinal study, this can be '2' to specify that this is the value of this variable at the second measurement moment. [Examples: <no example>] [Value description: A string that specifies another field in another entity (can be missing, i.e. NA).]
             uni.minimum = NA,                           ### Minimum value: If applicable, the minimum value in the data series of this variable. [Examples: 2.3; 643.2] [Value description: Any valid number]
             uni.maximum = NA,                           ### Maximum value: If applicable, the maximum value in the data series of this variable. [Examples: 2.3; 643.2] [Value description: Any valid number]
             uni.median = NA,                            ### Median value: If applicable, the median of this variable. [Examples: 2.3; 643.2] [Value description: Any valid number]
             uni.mean = NA,                              ### Mean value: If applicable, the mean of this variable. [Examples: 2.3; 643.2] [Value description: Any valid number]
             uni.percentage = NA,                        ### Percentage: If applicable, the percentage of observations in this category (for a categorical variable) or scoring TRUE (for a logical variable). [Examples: 2.3; 643.2] [Value description: Any valid number]
             uni.n = NA,                                 ### Sample size: This can be used to specify the sample size, if it is different from the sample size of the entire sample or the relevant subsample. [Examples: 30; 8762] [Value description: Any valid whole number]
             uni.sd = NA,                                ### Standard deviation: If applicable, the standard deviation of this variable. [Examples: 2.3; 643.2] [Value description: Any valid number]
             uni.qualitative = "",                       ### Qualitative: If applicable, the original text as extracted from the source material. [Examples: "Example"; "Another example"] [Value description: A single character value]
             uni.comment = "");                          ### Comment: Any relevant comments the coder wants to add [Examples: "Example"; "Another example"] [Value description: A single character value]
        
    ############################################################################
    study$results$univariate__1__[['validation']] <- list(`uni.name` = expression(!is.na(VALUE) && !is.null(VALUE) && (nchar(VALUE) > 0)),
                                                          `uni.variable` = expression(!is.null(FindNode(node$root, "oper.name"))),
                                                          `uni.subsample` = expression(is.na(VALUE) || (is.na(VALUE) || !is.null(FindNode(node$root, "subsample.name")))),
                                                          `uni.value` = expression("The extraction script is checked for existence of the field in the referent entity, if it is not NA"),
                                                          `uni.moment` = expression("The extraction script is checked for existence of the field in the referent entity, if it is not NA"),
                                                          `uni.minimum` = expression(is.na(VALUE) || (is.numeric(VALUE) && (length(VALUE) == 1))),
                                                          `uni.maximum` = expression(is.na(VALUE) || (is.numeric(VALUE) && (length(VALUE) == 1))),
                                                          `uni.median` = expression(is.na(VALUE) || (is.numeric(VALUE) && (length(VALUE) == 1))),
                                                          `uni.mean` = expression(is.na(VALUE) || (is.numeric(VALUE) && (length(VALUE) == 1))),
                                                          `uni.percentage` = expression(is.na(VALUE) || (is.numeric(VALUE) && (length(VALUE) == 1))),
                                                          `uni.n` = expression(is.na(VALUE) || (is.numeric(VALUE) && (VALUE%%1==0) && (length(VALUE) == 1))),
                                                          `uni.sd` = expression(is.na(VALUE) || (is.numeric(VALUE) && (length(VALUE) == 1))),
                                                          `uni.qualitative` = expression(is.na(VALUE) || (is.character(VALUE) && length(VALUE) == 1)),
                                                          `uni.comment` = expression(is.na(VALUE) || (is.character(VALUE) && length(VALUE) == 1)));
    study$results$univariate__1__$name <- study$results$univariate__1__$value[[1]];
    ############################################################################
    ############################################ END: univariate (REPEATING) ###
    ############################################################################
  
  
    ############################################################################
    ######################################### START: association (REPEATING) ###
    ############################################################################
    study$results$AddChild('association__1__');
    study$results$association__1__[['value']] <-
    ############################################################################
    ### 
    ### ASSOCIATION
    ### 
    ### An association between two variables.
    ### 
    ############################################################################
        
        list(assoc.name = "Enter name here (mandatory)",   ### Name of result: A unique name (in this study), to easily find / meta-analyse / group this result later [Examples: "mainHypothesisTest"; "manipulationCheck"] [Value description: A single character value that cannot be omitted]
             assoc.var1name = "enter <<entityRef>> here",  ### First variable: The name of the first variable. [Examples: <no example>] [Value description: A string that specifies another entity and which MUST be provided]
             assoc.var1values = NA,                        ### Values of first variable: Values this variable pertains to (e.g. in post hoc analyses). [Examples: <no example>] [Value description: A string that specifies another field in another entity (can be missing, i.e. NA).]
             assoc.var1moment = NA,                        ### Measurement moment of first variable: To which measurement moment of the first variable this association pertains. [Examples: <no example>] [Value description: A string that specifies another field in another entity (can be missing, i.e. NA).]
             assoc.var2name = "enter <<entityRef>> here",  ### Second variable: The name of the second variable. [Examples: <no example>] [Value description: A string that specifies another entity and which MUST be provided]
             assoc.var2values = NA,                        ### Values of second variable: Values this variable pertains to (e.g. in post hoc analyses). [Examples: <no example>] [Value description: A string that specifies another field in another entity (can be missing, i.e. NA).]
             assoc.var2moment = NA,                        ### Measurement moment of second variable: To which measurement moment of the second variable this association pertains. [Examples: <no example>] [Value description: A string that specifies another field in another entity (can be missing, i.e. NA).]
             assoc.subsample = NA,                         ### Subsample: If applicable, the subsample this result pertains to. [Examples: <no example>] [Value description: A string that specifies another entity (can be missing, i.e. NA)]
             assoc.n = NA,                                 ### Sample size: This can be used to specify the sample size, if it is different from the sample size of the entire sample or the relevant subsample. [Examples: 30; 8762] [Value description: Any valid whole number]
             assoc.df = NA,                                ### Degrees of freedom: This can be used to specify the degrees of freedom for this analysis, in case for example a t or an F value is extracted. [Examples: c(23.43, 62); 52.2; c(76, 12.56, 42)] [Value description: A vector of valid numbers]
             assoc.t = NA,                                 ### t value: The t value of this association. [Examples: 2.3; 643.2] [Value description: Any valid number]
             assoc.F = NA,                                 ### F value: The F value of this association [Examples: 2.3; 643.2] [Value description: Any valid number]
             assoc.r = NA,                                 ### Pearson r: The bivariate correlation of this association [Examples: 2.3; 643.2] [Value description: Any valid number]
             assoc.chisq = NA,                             ### Chi square: The chi squared value of this association [Examples: 2.3; 643.2] [Value description: Any valid number]
             assoc.crosstab = NA,                          ### Raw table: A table with the frequencies [Examples: rawTable(10, 5, 15, 10); rawTable(31, 87, 21, 54, 25, 32, ncol=3)] [Value description: A table with frequencies; variable 1 in columns, variable 2 in rows; always work from absence/negative/less (left, top) to presence/positive/more (right, bottom)]
             assoc.d = NA,                                 ### Cohen's d: The Cohen's d value of this association [Examples: 2.3; 643.2] [Value description: Any valid number]
             assoc.etasq = NA,                             ### Eta squared: The eta squared value of this association [Examples: 2.3; 643.2] [Value description: Any valid number]
             assoc.omegasq = NA,                           ### Omega squared: The omega squared value of this association [Examples: 2.3; 643.2] [Value description: Any valid number]
             assoc.OR = NA,                                ### Odds Ratio: The odds ratio of this association [Examples: 2.3; 643.2] [Value description: Any valid number]
             assoc.p = NA,                                 ### p value: The association's p value (only extract if nothing else is available) [Examples: 2.3; 643.2] [Value description: Any valid number]
             assoc.covariates = NA,                        ### Covariates: Number of covariates (for multivariate analyses). [Examples: 30; 8762] [Value description: Any valid whole number]
             assoc.comment = "");                          ### Comment: Any relevant comments the coder wants to add [Examples: "Example"; "Another example"] [Value description: A single character value]
        
    ############################################################################
    study$results$association__1__[['validation']] <- list(`assoc.name` = expression(!is.na(VALUE) && !is.null(VALUE) && (nchar(VALUE) > 0)),
                                                           `assoc.var1name` = expression(!is.null(FindNode(node$root, "oper.name"))),
                                                           `assoc.var1values` = expression("The extraction script is checked for existence of the field in the referent entity, if it is not NA"),
                                                           `assoc.var1moment` = expression("The extraction script is checked for existence of the field in the referent entity, if it is not NA"),
                                                           `assoc.var2name` = expression(!is.null(FindNode(node$root, "oper.name"))),
                                                           `assoc.var2values` = expression("The extraction script is checked for existence of the field in the referent entity, if it is not NA"),
                                                           `assoc.var2moment` = expression("The extraction script is checked for existence of the field in the referent entity, if it is not NA"),
                                                           `assoc.subsample` = expression(is.na(VALUE) || (is.na(VALUE) || !is.null(FindNode(node$root, "subsample.name")))),
                                                           `assoc.n` = expression(is.na(VALUE) || (is.numeric(VALUE) && (VALUE%%1==0) && (length(VALUE) == 1))),
                                                           `assoc.df` = expression(is.na(VALUE) || (is.numeric(VALUE))),
                                                           `assoc.t` = expression(is.na(VALUE) || (is.numeric(VALUE) && (length(VALUE) == 1))),
                                                           `assoc.F` = expression(is.na(VALUE) || (is.numeric(VALUE) && (length(VALUE) == 1))),
                                                           `assoc.r` = expression(is.na(VALUE) || (is.numeric(VALUE) && (length(VALUE) == 1))),
                                                           `assoc.chisq` = expression(is.na(VALUE) || (is.numeric(VALUE) && (length(VALUE) == 1))),
                                                           `assoc.crosstab` = expression(is.na(VALUE) || (class(VALUE) == "matrix")),
                                                           `assoc.d` = expression(is.na(VALUE) || (is.numeric(VALUE) && (length(VALUE) == 1))),
                                                           `assoc.etasq` = expression(is.na(VALUE) || (is.numeric(VALUE) && (length(VALUE) == 1))),
                                                           `assoc.omegasq` = expression(is.na(VALUE) || (is.numeric(VALUE) && (length(VALUE) == 1))),
                                                           `assoc.OR` = expression(is.na(VALUE) || (is.numeric(VALUE) && (length(VALUE) == 1))),
                                                           `assoc.p` = expression(is.na(VALUE) || (is.numeric(VALUE) && (length(VALUE) == 1))),
                                                           `assoc.covariates` = expression(is.na(VALUE) || (is.numeric(VALUE) && (VALUE%%1==0) && (length(VALUE) == 1))),
                                                           `assoc.comment` = expression(is.na(VALUE) || (is.character(VALUE) && length(VALUE) == 1)));
    study$results$association__1__$name <- study$results$association__1__$value[[1]];
    ############################################################################
    ########################################### END: association (REPEATING) ###
    ############################################################################
  
      
  ##############################################################################
  ############################################################# END: results ###
  ##############################################################################

    
################################################################################
########################################################## END: study (ROOT) ###
################################################################################
class(study) <- c('rxs', class(study));
```


```{r show-extracted-data-chunk, results='asis'}
print.rxs(study);
```

```{r validation-chunk, results='asis'}
rxs_validation(study);
pandoc.header('Validation results', level=1)
#rxs_validation(study,
#               rxsStructure = fullResults$rxsStructure);
if (length(study$validationResults) > 2) {
  cat(paste0('- ', study$validationResults), sep='
');
} else {
  cat('Validation successful!');
}
```

